FROM golang:1.24 AS builder

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o /out/backuper-receiver ./cmd/server

FROM gcr.io/distroless/base-debian12

WORKDIR /app
COPY --from=builder /out/backuper-receiver /app/backuper-receiver

EXPOSE 9000

ENTRYPOINT ["/app/backuper-receiver"]
